# Generated by Django 5.2.4 on 2026-02-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='created_at',
        ),
        migrations.AddField(
            model_name='game',
            name='human_color',
            field=models.CharField(default='white', max_length=5),
        ),
    ]
