# Generated by Django 5.2.4 on 2026-03-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_move_created_at_game_human_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='difficulty',
            field=models.IntegerField(default=10),
        ),
    ]
