# Generated by Django 5.2.4 on 2026-03-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(default='competitive', max_length=20),
        ),
    ]
